// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8w-aOnHXDgPQ1u5DkgAh26BRUxBu5RmM',
    appId: '1:551056648202:web:e385fce0105249225117f3',
    messagingSenderId: '551056648202',
    projectId: 'dictionarydox',
    authDomain: 'dictionarydox.firebaseapp.com',
    storageBucket: 'dictionarydox.appspot.com',
    measurementId: 'G-NTCTYCF50F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYwZo94GLUatXvwk6GbEK0R-eJwuZaEgk',
    appId: '1:551056648202:android:3703ca3c8a0b8ea15117f3',
    messagingSenderId: '551056648202',
    projectId: 'dictionarydox',
    storageBucket: 'dictionarydox.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAArOKlLxTMj5JSKkSQiW9LRIaQ06n6UTU',
    appId: '1:551056648202:ios:d9a777d318e942655117f3',
    messagingSenderId: '551056648202',
    projectId: 'dictionarydox',
    storageBucket: 'dictionarydox.appspot.com',
    iosClientId: '551056648202-sa56fq00eo9a4els0286vq8tc355trjd.apps.googleusercontent.com',
    iosBundleId: 'app.dicitionarydox.uz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAArOKlLxTMj5JSKkSQiW9LRIaQ06n6UTU',
    appId: '1:551056648202:ios:3b0342bc661fbc785117f3',
    messagingSenderId: '551056648202',
    projectId: 'dictionarydox',
    storageBucket: 'dictionarydox.appspot.com',
    iosClientId: '551056648202-5su31eja3bjqlrt08rliri1201tm0qtq.apps.googleusercontent.com',
    iosBundleId: 'com.example.dictionarydox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8w-aOnHXDgPQ1u5DkgAh26BRUxBu5RmM',
    appId: '1:551056648202:web:a9e05ccfa50f3b205117f3',
    messagingSenderId: '551056648202',
    projectId: 'dictionarydox',
    authDomain: 'dictionarydox.firebaseapp.com',
    storageBucket: 'dictionarydox.appspot.com',
    measurementId: 'G-ZMJQFRKJ57',
  );
}
