// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:dictionarydox/src/config/constants.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// Note: Firebase web config values are public and safe to expose in client-side code
// They are already visible in firebase-messaging-sw.js

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web {
    // On web, use values from AppConstants
    // These values are safe to expose in web builds as they're public Firebase config
    return FirebaseOptions(
      apiKey: AppConstants.firebaseWebApiKey,
      appId: AppConstants.firebaseWebAppId,
      messagingSenderId: AppConstants.firebaseWebMessagingSenderId,
      projectId: AppConstants.firebaseWebProjectId,
      authDomain: AppConstants.firebaseWebAuthDomain,
      storageBucket: AppConstants.firebaseWebStorageBucket,
      measurementId: AppConstants.firebaseWebMeasurementId,
    );
  }

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: AppConstants.firebaseAndroidApiKey,
        appId: AppConstants.firebaseAndroidAppId,
        messagingSenderId: AppConstants.firebaseAndroidMessagingSenderId,
        projectId: AppConstants.firebaseAndroidProjectId,
        storageBucket: AppConstants.firebaseAndroidStorageBucket,
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: AppConstants.firebaseIosApiKey,
        appId: AppConstants.firebaseIosAppId,
        messagingSenderId: AppConstants.firebaseIosMessagingSenderId,
        projectId: AppConstants.firebaseIosProjectId,
        storageBucket: AppConstants.firebaseIosStorageBucket,
        iosClientId: AppConstants.firebaseIosClientId,
        iosBundleId: AppConstants.firebaseIosBundleId,
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: AppConstants.firebaseMacosApiKey,
        appId: AppConstants.firebaseMacosAppId,
        messagingSenderId: AppConstants.firebaseMacosMessagingSenderId,
        projectId: AppConstants.firebaseMacosProjectId,
        storageBucket: AppConstants.firebaseMacosStorageBucket,
        iosClientId: AppConstants.firebaseMacosClientId,
        iosBundleId: AppConstants.firebaseMacosBundleId,
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: AppConstants.firebaseWindowsApiKey,
        appId: AppConstants.firebaseWindowsAppId,
        messagingSenderId: AppConstants.firebaseWindowsMessagingSenderId,
        projectId: AppConstants.firebaseWindowsProjectId,
        authDomain: AppConstants.firebaseWindowsAuthDomain,
        storageBucket: AppConstants.firebaseWindowsStorageBucket,
        measurementId: AppConstants.firebaseWindowsMeasurementId,
      );
}
